USE indicadores_ods;
DELETE FROM agrupamientoRefGeografica;
DELETE FROM refGeografica;
ALTER TABLE refGeografica AUTO_INCREMENT=0;
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (0, 'PAIS', 'N');
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (1, 'BUENOS AIRES', 'P'); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (2, 'CATAMARCA', 'P'); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (3, 'CHACO', 'P'); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (4, 'CHUBUT', 'P'); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (5, 'CIUDAD AUTONOMA DE BUENOS AIRES', 'P'); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (6, 'CORDOBA', 'P'); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (7, 'CORRIENTES', 'P'); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (8, 'ENTRE RIOS', 'P'); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (9, 'FORMOSA', 'P'); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (10, 'JUJUY', 'P'); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (11, 'LA PAMPA', 'P'); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (12, 'LA RIOJA', 'P'); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (13, 'MENDOZA', 'P'); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (14, 'MISIONES', 'P'); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (15, 'NEUQUEN', 'P'); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (16, 'RIO NEGRO', 'P'); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (17, 'SALTA', 'P'); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (18, 'SAN JUAN', 'P'); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (19, 'SAN LUIS', 'P'); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (20, 'SANTA CRUZ', 'P'); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (21, 'SANTA FE', 'P'); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (22, 'SANTIAGO DEL ESTERO', 'P'); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (23, 'TIERRA DEL FUEGO', 'P'); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (24, 'TUCUMAN', 'P'); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (25, "CONCORDIA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (25, 8); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (26, "SAN SALVADOR", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (26, 8); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (27, "VILLAGUAY", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (27, 8); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (28, "COLON", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (28, 8); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (29, "FEDERAL", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (29, 8); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (30, "CAPITAL", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (30, 7); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (31, "ALMIRANTE BROWN", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (31, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (32, "NOGOYA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (32, 8); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (33, "ITATI", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (33, 7); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (34, "ATREUCO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (34, 11); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (35, "TALA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (35, 8); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (36, "CAINGUAS", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (36, 14); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (37, "LEANDRO N. ALEM", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (37, 14); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (38, "PRESIDENTE ROQUE SAENZ PENA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (38, 6); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (39, "GUALEGUAYCHU", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (39, 8); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (40, "BERON DE ASTRADA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (40, 7); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (41, "QUITILIPI", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (41, 3); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (42, "ISLAS DEL IBICUY", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (42, 8); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (43, "GUALEGUAY", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (43, 8); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (44, "FEDERACION", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (44, 8); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (45, "LA PAZ", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (45, 8); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (46, "FELICIANO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (46, 8); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (47, "GENERAL PAZ", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (47, 7); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (48, "PRESIDENCIA DE LA PLAZA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (48, 3); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (49, "VICTORIA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (49, 8); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (50, "SAN LORENZO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (50, 3); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (51, "CAPAYAN", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (51, 2); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (52, "DIAMANTE", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (52, 8); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (53, "MONTECARLO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (53, 14); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (54, "LA PLATA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (54, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (55, "CORONEL FELIPE VARELA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (55, 12); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (56, "URUGUAY", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (56, 8); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (57, "PRESIDENTE PERON", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (57, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (58, "PARANA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (58, 8); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (59, "MERCEDES", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (59, 7); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (60, "APOSTOLES", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (60, 14); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (61, "CANDELARIA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (61, 14); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (62, "CARLOS CASARES", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (62, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (63, "SALADILLO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (63, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (64, "LIBERTADOR GENERAL SAN MARTIN", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (64, 14); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (65, "CAPITAL", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (65, 14); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (66, "CONCEPCION", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (66, 7); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (67, "O'HIGGINS", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (67, 3); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (68, "ELDORADO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (68, 14); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (69, "SAN ROQUE", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (69, 7); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (70, "SALADAS", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (70, 7); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (71, "MBURUCUYA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (71, 7); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (72, "SAN LUIS DEL PALMAR", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (72, 7); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (73, "SAN PEDRO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (73, 14); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (74, "SANTO TOME", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (74, 7); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (75, "PEHUAJO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (75, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (76, "TRENQUE LAUQUEN", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (76, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (77, "GENERAL BELGRANO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (77, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (78, "LAS FLORES", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (78, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (79, "GENERAL ALVEAR", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (79, 7); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (80, "SAN MARTIN", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (80, 7); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (81, "PASO DE LOS LIBRES", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (81, 7); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (82, "MONTE CASEROS", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (82, 7); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (83, "GENERAL GUIDO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (83, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (84, "CURUZU CUATIA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (84, 7); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (85, "SAUCE", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (85, 7); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (86, "ESQUINA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (86, 7); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (87, "ITUZAINGO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (87, 7); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (88, "OLAVARRIA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (88, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (89, "SAN MIGUEL", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (89, 7); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (90, "GOYA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (90, 7); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (91, "LAVALLE", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (91, 7); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (92, "BELLA VISTA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (92, 7); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (93, "EMPEDRADO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (93, 7); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (94, "ROJAS", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (94, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (95, "SAN ANTONIO DE ARECO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (95, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (96, "MAIPU", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (96, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (97, "9 DE JULIO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (97, 3); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (98, "ARRECIFES", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (98, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (99, "2 DE ABRIL", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (99, 3); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (100, "CAPITAN SARMIENTO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (100, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (101, "CARMEN DE ARECO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (101, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (102, "PINAMAR", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (102, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (103, "SALTO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (103, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (104, "EXALTACION DE LA CRUZ", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (104, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (105, "TAPENAGA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (105, 3); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (106, "ESCOBAR", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (106, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (107, "SAN MIGUEL", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (107, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (108, "SAN ANDRES DE GILES", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (108, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (109, "JUNIN", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (109, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (110, "MERCEDES", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (110, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (111, "GENERAL VILLEGAS", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (111, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (112, "PILAR", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (112, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (113, "LUJAN", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (113, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (114, "HURLINGHAM", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (114, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (115, "MORON", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (115, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (116, "CHACABUCO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (116, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (117, "MALVINAS ARGENTINAS", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (117, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (118, "JOSE C PAZ", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (118, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (119, "GENERAL SAN MARTIN", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (119, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (120, "MORENO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (120, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (121, "LINCOLN", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (121, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (122, "ITUZAINGO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (122, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (123, "FLORENTINO AMEGHINO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (123, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (124, "LA MATANZA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (124, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (125, "RIVADAVIA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (125, 18); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (126, "GENERAL RODRIGUEZ", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (126, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (127, "SUIPACHA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (127, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (128, "TRES DE FEBRERO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (128, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (129, "MERLO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (129, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (130, "CHIVILCOY", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (130, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (131, "BRAGADO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (131, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (132, "LANUS", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (132, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (133, "GENERAL LAS HERAS", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (133, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (134, "MARCOS PAZ", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (134, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (135, "LOMAS DE ZAMORA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (135, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (136, "GENERAL VIAMONTE", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (136, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (137, "ESTEBAN ECHEVERRIA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (137, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (138, "EZEIZA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (138, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (139, "ALBERTI", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (139, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (140, "FLORENCIO VARELA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (140, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (141, "NAVARRO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (141, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (142, "SANTA LUCIA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (142, 18); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (143, "CAÑUELAS", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (143, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (144, "SAN VICENTE", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (144, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (145, "LOBOS", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (145, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (146, "BRANDSEN", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (146, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (147, "CARLOS TEJEDOR", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (147, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (148, "25 DE MAYO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (148, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (149, "9 DE JULIO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (149, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (150, "GENERAL PAZ", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (150, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (151, "MONTE", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (151, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (152, "ROQUE PEREZ", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (152, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (153, "GENERAL ALVEAR", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (153, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (154, "QUILMES", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (154, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (155, "PILA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (155, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (156, "GENERAL LA MADRID", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (156, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (157, "BOLIVAR", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (157, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (158, "BALCARCE", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (158, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (159, "VICENTE LOPEZ", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (159, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (160, "CAPITAL", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (160, 18); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (161, "TAPALQUE", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (161, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (162, "HIPOLITO YRIGOYEN", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (162, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (163, "DOLORES", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (163, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (164, "RAUCH", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (164, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (165, "AZUL", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (165, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (166, "DAIREAUX", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (166, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (167, "TRES LOMAS", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (167, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (168, "AYACUCHO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (168, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (169, "GUAMINI", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (169, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (170, "SALLIQUELO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (170, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (171, "GENERAL JUAN MADARIAGA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (171, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (172, "ENSENADA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (172, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (173, "BERAZATEGUI", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (173, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (174, "TANDIL", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (174, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (175, "GUAYMALLEN", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (175, 13); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (176, "CORONEL SUAREZ", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (176, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (177, "LAPRIDA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (177, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (178, "AVELLANEDA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (178, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (179, "SAN ISIDRO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (179, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (180, "BENITO JUAREZ", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (180, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (181, "SAAVEDRA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (181, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (182, "ADOLFO GONZALES CHAVES", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (182, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (183, "CORONEL PRINGLES", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (183, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (184, "TORNQUIST", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (184, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (185, "TIGRE", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (185, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (186, "GENERAL PINTO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (186, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (187, "SAN CAYETANO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (187, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (188, "TRES ARROYOS", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (188, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (189, "CORONEL DE MARINA LEONARDO ROSALES", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (189, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (190, "VILLA GESELL", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (190, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (191, "BAHIA BLANCA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (191, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (192, "MONTE HERMOSO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (192, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (193, "CORONEL DORREGO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (193, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (194, "NECOCHEA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (194, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (195, "LOBERIA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (195, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (196, "GENERAL ALVARADO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (196, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (197, "CHASCOMUS", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (197, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (198, "BERISSO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (198, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (199, "GENERAL PUEYRREDON", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (199, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (200, "MAR CHIQUITA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (200, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (201, "LA COSTA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (201, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (202, "GENERAL LAVALLE", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (202, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (203, "TORDILLO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (203, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (204, "CASTELLI", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (204, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (205, "PUNTA INDIO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (205, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (206, "MAGDALENA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (206, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (207, "SAN FERNANDO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (207, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (208, "CAMPANA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (208, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (209, "BARADERO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (209, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (210, "ZARATE", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (210, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (211, "SAN PEDRO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (211, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (212, "RAMALLO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (212, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (213, "SAN NICOLAS", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (213, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (214, "PERGAMINO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (214, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (215, "FIGUEROA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (215, 22); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (216, "COLON", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (216, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (217, "AVELLANEDA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (217, 22); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (218, "PELLEGRINI", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (218, 22); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (219, "SALAVINA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (219, 22); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (220, "GENERAL TABOADA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (220, 22); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (221, "ALBERDI", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (221, 22); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (222, "MORENO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (222, 22); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (223, "ZONDA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (223, 18); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (224, "JUAN F IBARRA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (224, 22); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (225, "CHOYA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (225, 22); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (226, "AYACUCHO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (226, 19); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (227, "RIVADAVIA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (227, 22); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (228, "OJO DE AGUA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (228, 22); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (229, "GOBERNADOR DUPUY", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (229, 19); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (230, "ULLUM", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (230, 18); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (231, "ANGACO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (231, 18); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (232, "ALBARDON", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (232, 18); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (233, "CHIMBAS", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (233, 18); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (234, "9 DE JULIO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (234, 18); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (235, "RAWSON", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (235, 18); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (236, "POCITO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (236, 18); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (237, "SAN MARTIN", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (237, 18); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (238, "CAUCETE", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (238, 18); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (239, "JACHAL", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (239, 18); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (240, "TERCERO ARRIBA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (240, 6); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (241, "25 DE MAYO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (241, 18); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (242, "JUAREZ CELMAN", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (242, 6); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (243, "CAPITAL", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (243, 17); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (244, "CACHI", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (244, 17); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (245, "CERRILLOS", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (245, 17); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (246, "CHICOANA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (246, 17); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (247, "LA VIÑA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (247, 17); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (248, "SANTA VICTORIA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (248, 17); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (249, "GENERAL JOSE DE SAN MARTIN", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (249, 17); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (250, "SANTA ROSA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (250, 13); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (251, "RIVADAVIA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (251, 17); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (252, "METAN", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (252, 17); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (253, "LA CANDELARIA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (253, 17); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (254, "MAIPU", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (254, 13); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (255, "GUACHIPAS", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (255, 17); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (256, "CAPITAL", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (256, 13); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (257, "GODOY CRUZ", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (257, 13); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (258, "CAFAYATE", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (258, 17); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (259, "JUNIN", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (259, 13); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (260, "RIVADAVIA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (260, 13); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (261, "GENERAL ALVEAR", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (261, 13); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (262, "MOLINOS", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (262, 17); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (263, "CASTRO BARROS", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (263, 12); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (264, "GENERAL GÜEMES", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (264, 17); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (265, "SANAGASTA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (265, 12); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (266, "SAN CARLOS", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (266, 17); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (267, "GENERAL OCAMPO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (267, 12); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (268, "ROSARIO DE LERMA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (268, 17); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (269, "SAN MARTIN", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (269, 13); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (270, "LA PAZ", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (270, 13); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (271, "SAN RAFAEL", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (271, 13); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (272, "CHILECITO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (272, 12); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (273, "GENERAL ANGEL V. PEÑALOZA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (273, 12); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (274, "GENERAL BELGRANO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (274, 12); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (275, "CHAMICAL", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (275, 12); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (276, "INDEPENDENCIA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (276, 12); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (277, "GENERAL JUAN F. QUIROGA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (277, 12); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (278, "ROSARIO VERA PEÑALOZA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (278, 12); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (279, "GENERAL SAN MARTIN", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (279, 12); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (280, "VINCHINA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (280, 12); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (281, "FAMATINA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (281, 12); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (282, "LIBERTAD", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (282, 3); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (283, "SAN BLAS DE LOS SAUCES", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (283, 12); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (284, "ARAUCO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (284, 12); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (285, "REALICO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (285, 11); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (286, "TRENEL", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (286, 11); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (287, "CHALILEO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (287, 11); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (288, "LOVENTUE", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (288, 11); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (289, "TOAY", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (289, 11); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (290, "CAPITAL", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (290, 11); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (291, "LIMAY MAHUIDA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (291, 11); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (292, "UTRACAN", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (292, 11); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (293, "MAYOR LUIS J. FONTANA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (293, 3); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (294, "CURACO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (294, 11); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (295, "FRAY JUSTO SANTA MARIA DE ORO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (295, 3); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (296, "LIHUEL CALEL", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (296, 11); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (297, "RANCUL", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (297, 11); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (298, "CONHELO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (298, 11); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (299, "TILCARA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (299, 10); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (300, "PALPALA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (300, 10); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (301, "COCHINOCA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (301, 10); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (302, "TUMBAYA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (302, 10); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (303, "DOCTOR MANUEL BELGRANO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (303, 10); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (304, "SAN ANTONIO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (304, 10); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (305, "EL CARMEN", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (305, 10); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (306, "SANTA BARBARA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (306, 10); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (307, "LEDESMA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (307, 10); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (308, "HUMAHUACA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (308, 10); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (309, "YAVI", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (309, 10); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (310, "SANTA CATALINA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (310, 10); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (311, "SAN PEDRO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (311, 10); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (312, "12 DE OCTUBRE", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (312, 3); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (313, "VALLE GRANDE", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (313, 10); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (314, "RINCONADA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (314, 10); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (315, "CHACABUCO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (315, 3); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (316, "RAMON LISTA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (316, 9); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (317, "PILCOMAYO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (317, 9); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (318, "FORMOSA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (318, 9); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (319, "CAPITAL", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (319, 2); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (320, "ANCASTI", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (320, 2); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (321, "BELEN", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (321, 2); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (322, "SANTA MARIA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (322, 2); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (323, "ANDALGALA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (323, 2); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (324, "AMBATO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (324, 2); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (325, "PACLIN", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (325, 2); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (326, "SANTA ROSA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (326, 2); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (327, "EL ALTO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (327, 2); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (328, "SOBREMONTE", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (328, 6); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (329, "LA PAZ", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (329, 2); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (330, "POMAN", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (330, 2); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (331, "RIO GRANDE", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (331, 23); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (332, "MARTIRES", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (332, 4); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (333, "PASO DE INDIOS", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (333, 4); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (334, "MAGALLANES", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (334, 20); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (335, "SARGENTO CABRAL", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (335, 3); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (336, "COMANDANTE FERNANDEZ", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (336, 3); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (337, "INDEPENDENCIA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (337, 3); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (338, "CORPEN AIKE", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (338, 20); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (339, "DESEADO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (339, 20); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (340, "CONESA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (340, 16); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (341, "LANGUIÑEO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (341, 4); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (342, "GAIMAN", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (342, 4); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (343, "GENERAL BELGRANO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (343, 3); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (344, "GENERAL DONOVAN", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (344, 3); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (345, "RAWSON", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (345, 4); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (346, "TEHUELCHES", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (346, 4); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (347, "ESCALANTE", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (347, 4); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (348, "FLORENTINO AMEGHINO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (348, 4); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (349, "25 DE MAYO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (349, 3); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (350, "GENERAL LAMADRID", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (350, 12); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (351, "CALINGASTA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (351, 18); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (352, "MAIPU", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (352, 3); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (353, "1° DE MAYO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (353, 3); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (354, "TULUMBA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (354, 6); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (355, "ISCHILIN", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (355, 6); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (356, "TOTORAL", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (356, 6); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (357, "CRUZ DEL EJE", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (357, 6); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (358, "COLON", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (358, 6); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (359, "PUNILLA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (359, 6); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (360, "CAPITAL", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (360, 6); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (361, "GENERAL SAN MARTIN", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (361, 6); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (362, "SANTA MARIA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (362, 6); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (363, "MINAS", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (363, 6); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (364, "POCHO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (364, 6); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (365, "SAN ALBERTO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (365, 6); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (366, "SAN JAVIER", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (366, 6); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (367, "RIO SEGUNDO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (367, 6); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (368, "SAN JUSTO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (368, 6); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (369, "UNION", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (369, 6); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (370, "RIO PRIMERO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (370, 6); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (371, "MARCOS JUAREZ", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (371, 6); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (372, "RIO CUARTO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (372, 6); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (373, "ANTOFAGASTA DE LA SIERRA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (373, 2); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (374, "TINOGASTA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (374, 2); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (375, "GENERAL ROCA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (375, 6); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (376, "LEANDRO N ALEM", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (376, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (377, "TUPUNGATO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (377, 13); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (378, "TUNUYAN", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (378, 13); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (379, "LUJAN DE CUYO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (379, 13); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (380, "FUTALEUFU", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (380, 4); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (381, "RIO CHICO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (381, 20); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (382, "LAGO ARGENTINO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (382, 20); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (383, "SAN JAVIER", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (383, 14); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (384, "CONCEPCION", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (384, 14); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (385, "GUARANI", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (385, 14); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (386, "GENERAL ARENALES", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (386, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (387, "25 DE MAYO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (387, 14); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (388, "OBERA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (388, 14); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (389, "GENERAL MANUEL BELGRANO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (389, 14); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (390, "SAN IGNACIO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (390, 14); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (391, "PIRANE", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (391, 9); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (392, "PATIÑO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (392, 9); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (393, "BERMEJO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (393, 9); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (394, "BERMEJO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (394, 3); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (395, "LIBERTADOR GENERAL SAN MARTIN", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (395, 3); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (396, "GENERAL GUEMES", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (396, 3); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (397, "PILAGAS", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (397, 9); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (398, "VALCHETA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (398, 16); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (399, "SAN ANTONIO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (399, 16); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (400, "LAISHI", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (400, 9); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (401, "9 DE JULIO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (401, 16); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (402, "ÑORQUINCO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (402, 16); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (403, "25 DE MAYO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (403, 16); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (404, "BIEDMA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (404, 4); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (405, "TELSEN", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (405, 4); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (406, "GASTRE", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (406, 4); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (407, "EL CUY", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (407, 16); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (408, "PILCANIYEU", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (408, 16); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (409, "CALAMUCHITA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (409, 6); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (410, "ADOLFO ALSINA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (410, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (411, "RIVADAVIA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (411, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (412, "PELLEGRINI", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (412, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (413, "PUAN", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (413, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (414, "VILLARINO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (414, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (415, "MARACO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (415, 11); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (416, "QUEMU QUEMU", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (416, 11); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (417, "CATRILO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (417, 11); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (418, "CALEU CALEU", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (418, 11); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (419, "GUATRACHE", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (419, 11); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (420, "HUCAL", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (420, 11); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (421, "PATAGONES", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (421, 1); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (422, "CHAPALEUFU", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (422, 11); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (423, "IGUAZU", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (423, 14); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (424, "IRIONDO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (424, 21); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (425, "SAN JUSTO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (425, 21); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (426, "LAS COLONIAS", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (426, 21); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (427, "SARMIENTO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (427, 18); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (428, "LAS HERAS", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (428, 13); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (429, "LAVALLE", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (429, 13); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (430, "MALARGÜE", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (430, 13); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (431, "SAN JERONIMO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (431, 21); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (432, "GENERAL LOPEZ", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (432, 21); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (433, "ROSARIO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (433, 21); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (434, "SAN LORENZO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (434, 21); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (435, "PICHI MAHUIDA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (435, 16); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (436, "ADOLFO ALSINA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (436, 16); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (437, "USHUAIA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (437, 23); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (438, "RIO SENGUER", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (438, 4); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (439, "BARILOCHE", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (439, 16); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (440, "GARAY", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (440, 21); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (441, "SAN JAVIER", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (441, 21); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (442, "VERA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (442, 21); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (443, "CASTELLANOS", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (443, 21); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (444, "BELGRANO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (444, 21); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (445, "CASEROS", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (445, 21); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (446, "9 DE JULIO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (446, 21); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (447, "SAN MARTIN", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (447, 21); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (448, "GENERAL OBLIGADO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (448, 21); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (449, "LA CAPITAL", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (449, 21); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (450, "CONSTITUCION", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (450, 21); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (451, "LOS ANDES", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (451, 17); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (452, "SUSQUES", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (452, 10); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (453, "SAN FERNANDO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (453, 3); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (454, "SAN COSME", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (454, 7); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (455, "LA POMA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (455, 17); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (456, "CHACABUCO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (456, 19); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (457, "JUAN MARTIN DE PUEYRREDON", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (457, 19); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (458, "GENERAL PEDERNERA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (458, 19); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (459, "LIBERTADOR GENERAL SAN MARTIN", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (459, 19); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (460, "CORONEL PRINGLES", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (460, 19); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (461, "JUNIN", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (461, 19); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (462, "LA CALDERA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (462, 17); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (463, "CAPITAL", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (463, 12); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (464, "HUILICHES", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (464, 15); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (465, "CATAN LIL", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (465, 15); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (466, "IRUYA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (466, 17); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (467, "ORAN", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (467, 17); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (468, "MATACOS", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (468, 9); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (469, "SILIPICA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (469, 22); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (470, "ANTA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (470, 17); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (471, "ALMIRANTE BROWN", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (471, 3); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (472, "COPO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (472, 22); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (473, "RIO HONDO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (473, 22); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (474, "ROSARIO DE LA FRONTERA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (474, 17); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (475, "RIO SECO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (475, 6); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (476, "VALLE FERTIL", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (476, 18); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (477, "IGLESIA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (477, 18); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (478, "AVELLANEDA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (478, 16); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (479, "GENERAL ROCA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (479, 16); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (480, "BELGRANO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (480, 19); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (481, "LOS LAGOS", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (481, 15); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (482, "LACAR", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (482, 15); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (483, "COLLON CURA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (483, 15); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (484, "PICUN LEUFU", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (484, 15); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (485, "ALUMINE", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (485, 15); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (486, "ZAPALA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (486, 15); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (487, "CONFLUENCIA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (487, 15); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (488, "PICUNCHES", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (488, 15); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (489, "AÑELO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (489, 15); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (490, "LONCOPUE", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (490, 15); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (491, "ÑORQUIN", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (491, 15); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (492, "PEHUENCHES", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (492, 15); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (493, "MINAS", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (493, 15); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (494, "CHOS MALAL", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (494, 15); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (495, "LA COCHA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (495, 24); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (496, "GRANEROS", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (496, 24); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (497, "JUAN BAUTISTA ALBERDI", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (497, 24); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (498, "RIO CHICO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (498, 24); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (499, "CHICLIGASTA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (499, 24); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (500, "SIMOCA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (500, 24); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (501, "LULES", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (501, 24); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (502, "MONTEROS", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (502, 24); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (503, "LEALES", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (503, 24); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (504, "FAMAILLA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (504, 24); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (505, "YERBA BUENA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (505, 24); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (506, "BURRUYACU", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (506, 24); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (507, "TAFI VIEJO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (507, 24); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (508, "TAFI DEL VALLE", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (508, 24); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (509, "ISLAS MALVINAS", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (509, 23); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (510, "CAPITAL", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (510, 24); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (511, "CRUZ ALTA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (511, 24); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (512, "COMUNA 6", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (512, 5); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (513, "TRANCAS", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (513, 24); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (514, "SARMIENTO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (514, 4); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (515, "SAN CRISTOBAL", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (515, 21); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (516, "CUSHAMEN", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (516, 4); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (517, "LAGO BUENOS AIRES", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (517, 20); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (518, "CHICAL CO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (518, 11); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (519, "PUELEN", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (519, 11); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (520, "COMUNA 1", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (520, 5); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (521, "ISLAS DEL ATLANTICO SUR", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (521, 23); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (522, "COMUNA 2", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (522, 5); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (523, "COMUNA 3", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (523, 5); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (524, "COMUNA 4", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (524, 5); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (525, "COMUNA 5", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (525, 5); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (526, "COMUNA 7", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (526, 5); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (527, "COMUNA 8", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (527, 5); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (528, "COMUNA 9", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (528, 5); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (529, "BANDA", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (529, 22); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (530, "COMUNA 10", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (530, 5); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (531, "COMUNA 11", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (531, 5); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (532, "COMUNA 12", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (532, 5); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (533, "ROBLES", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (533, 22); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (534, "CAPITAL", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (534, 22); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (535, "COMUNA 13", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (535, 5); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (536, "COMUNA 14", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (536, 5); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (537, "COMUNA 15", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (537, 5); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (538, "VALLE VIEJO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (538, 2); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (539, "FRAY MAMERTO ESQUIU", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (539, 2); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (540, "GÜER AIKE", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (540, 20); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (541, "SAN MARTIN", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (541, 22); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (542, "MITRE", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (542, 22); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (543, "SARMIENTO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (543, 22); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (544, "ATAMISQUI", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (544, 22); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (545, "LORETO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (545, 22); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (546, "GUASAYAN", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (546, 22); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (547, "JIMENEZ", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (547, 22); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (548, "QUEBRACHOS", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (548, 22); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (549, "BELGRANO", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (549, 22); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (550, "AGUIRRE", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (550, 22); 
INSERT INTO refGeografica (id, descripcion, ambito) VALUES (551, "SAN CARLOS", 'D'); 
INSERT INTO agrupamientoRefGeografica (id_1, id_2) VALUES (551, 13); 
