# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.form.registration:
        class: AppBundle\Form\UserRegisterType
        tags:
            - { name: form.type, alias: app_user_registration }
    app.form.profile:
        class: AppBundle\Form\UserProfileType
        tags:
            - { name: form.type, alias: app_user_profile }

    app.form.resetting:
        class: AppBundle\Form\UserRequestPasswordType
        tags:
            - { name: form.type, alias: app_user_request_password }

    app.utils.scopes_service:
        class: AppBundle\Utils\ScopesService
        arguments: ["@doctrine.orm.entity_manager","@security.token_storage"]
